<?php

namespace AppBundle\Repository;

/**
 * TstRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TstRepository extends \Doctrine\ORM\EntityRepository
{
}
