blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

my_first:
    resource: "@MyFirstBundle/Controller/"
    type:     annotation
    prefix:   /mf

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /dub

test:
      path: /dub/tp
      defaults: { _controller: AppBundle:Lucky:test }

