fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

# some routes must have '/' at the end
# otherwise an exception might be thrown - BlogBundle\Entity\Post object not found.
# Don't know the reason of it
stat:
    path: /statest/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:  AppBundle:Default:app_lucky_octo.html.twig

my_first:
    resource: "@MyFirstBundle/Controller/"
    type:     annotation
    prefix:   /mf

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /dub

test:
      path: /dub/tp
      defaults: { _controller: AppBundle:Lucky:test }
