blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

my_first:
    resource: "@MyFirstBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /dub

