services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    tst.serv:
        class: AppBundle\Extensions\TstService
        arguments: ["@doctrine"]